Repository CityOfBoston/boston.gov-d8, pull requests merged in 2022-12, with the labels that each got.

#2828 (develop) DIG-1463 Feedback form
  config/default/block.block.website_feedback_form.yml
  config/default/webform.webform.website_feedback_form.yml
  config/default/webform.webform_options.feedback_form.yml
  config/default/webform.webform_options.yes_no.yml
  docroot/themes/custom/bos_theme/css/bos_theme_overrides.css
Labels: Enhancement

#2848 DIG-1307
  docroot/themes/custom/bos_theme/css/bos_theme_overrides.css
  docroot/themes/custom/bos_theme/dist/js/all.js
Labels: Enhancement

#2851 DIG-1307 mobile tables update
  docroot/themes/custom/bos_theme/css/bos_theme_overrides.css
  docroot/themes/custom/bos_theme/dist/js/all.js
Labels: Drupal 9

#2855 DIG-1307 mobile tables update
  docroot/themes/custom/bos_theme/css/bos_theme_overrides.css
Labels: Enhancement

#2862 DIG-1545 Feedback form
  composer.json
  composer.lock
  config/acquia_dev/acquia_connector.settings.yml
  config/acquia_prod/acquia_connector.settings.yml
  config/acquia_stage/acquia_connector.settings.yml
  config/default/block.block.webform_2.yml
  config/default/config_split.config_split.local.yml
  config/default/core.extension.yml
  config/default/editor.editor.basic_html.yml
  config/default/editor.editor.filtered_html.yml
  config/default/editor.editor.full_html.yml
  config/default/editor.editor.rich_text.yml
  config/default/views.view.bhmaps.yml
  config/default/webform.webform.metrolist_listing.yml
  config/default/webform.webform.website_feedback_form.yml
  docroot/modules/custom/bos_content/modules/bos_metrolist/bos_metrolist.module
  docroot/modules/custom/bos_content/modules/bos_metrolist/src/Plugin/WebformHandler/CreateMetroListingWebformHandler.php
Labels: Front End/UI

#2864 [develop] DIG-1547 update to availability screen options
  config/default/webform.webform.metrolist_listing.yml
Labels: Metrolist

#2861 DIG-1307 Mobile tables update
  docroot/themes/custom/bos_theme/css/bos_theme_overrides.css
  docroot/themes/custom/bos_theme/dist/js/all.js
Labels: Enhancement, Front End/UI

#2866 DIG-1545 bug fix - wrong ID used
  config/acquia_dev/config_ignore.settings.yml
  config/acquia_prod/config_ignore.settings.yml
  config/acquia_stage/config_ignore.settings.yml
  config/default/webform.webform.website_feedback_form.yml
Labels: Bug, Enhancement

#2870 DIG-883 Add theme selection to drupal admin
  config/default/core.entity_form_display.paragraph.cabinet.default.yml
  config/default/core.entity_form_display.paragraph.text.default.yml
Labels: Enhancement
