Repository CityOfBoston/boston.gov-d8, pull requests merged in 2022-06, with the labels that each got.

#2523 Maintenance 2022 06 01
  composer.json
  composer.lock
  config/acquia_dev/config_ignore.settings.yml
  config/acquia_prod/config_ignore.settings.yml
  config/acquia_prod/redirect_domain.domains.yml
  config/acquia_stage/config_ignore.settings.yml
  config/default/config_split.config_split.acquia_dev.yml
  config/default/config_split.config_split.acquia_prod.yml
  config/default/config_split.config_split.acquia_stage.yml
  config/default/config_split.config_split.local.yml
  config/default/config_split.config_split.travis.yml
  config/default/user.role.authenticated.yml
  config/default/user.role.content_author.yml
  config/default/user.role.developer.yml
  config/default/user.role.site_administrator.yml
  config/local/config_ignore.settings.yml
  config/local/config_split.patch.user.role.site_administrator.yml
  config/local/simplesamlphp_auth.settings.yml
  config/travis/config_ignore.settings.yml
Labels: Maintenance

#2532 Change field in "person profile" content type
  config/default/core.base_field_override.node.person_profile.title.yml
Labels: Enhancement, Back End

#2533 Make CSS consistent / the same on back-end and front-end
  docroot/themes/custom/bos_theme/css/bos_theme_overrides.css
Labels: Bug

#2534 Security update core to 9.3.16
  composer.lock
Labels: Maintenance

#2535 [DEPLOY TO STAGE] Core 9.3.16
  composer.lock
Labels: Maintenance

#2537 [DEPLOY TO STAGE] manifest Icons bug
  docroot/modules/custom/bos_core/src/Plugin/QueueWorker/IconManifestProcessBase.php
Labels: Bug

#2542 [DEPLOY TO STAGE] Maintenance
  composer.lock
Labels: Maintenance

#2543 https://bostondoit.atlassian.net/jira/software/c/projects/DIG/boards/…
  docroot/modules/custom/bos_content/modules/node_public_notice/node_public_notice.module
Labels: Enhancement

#2544 Public notices featured
  config/default/core.entity_view_display.node.public_notice.featured_item.yml
  docroot/themes/custom/bos_theme/css/bos_theme_overrides.css
Labels: Enhancement

#2546 Css template tickets
  config/default/core.base_field_override.node.person_profile.title.yml
  config/default/core.entity_view_display.node.public_notice.featured_item.yml
  docroot/modules/custom/bos_components/modules/bos_news_and_announcements/templates/views-view-fields--news-and-announcements.html.twig
  docroot/modules/custom/bos_components/modules/bos_web_app/apps/my_neighborhood/dist/index.js
  docroot/modules/custom/bos_components/modules/bos_web_app/apps/my_neighborhood/src/js/app/mnl_config.js
  docroot/modules/custom/bos_content/modules/node_how_to/css/node_how_to.css
  docroot/modules/custom/bos_content/modules/node_public_notice/node_public_notice.module
  docroot/modules/custom/bos_content/modules/node_public_notice/templates/node--public-notice--featured-item.html.twig
  docroot/modules/custom/bos_vocab/modules/vocab_contact/templates/field--field-email.html.twig
  docroot/themes/custom/bos_theme/css/bos_theme_overrides.css
  scripts/deploy/travis_deploy.sh
Labels: Bug, Enhancement, Front End/UI, Back End

#2551 Events and Notices bug fix
  docroot/modules/custom/bos_content/modules/node_event/templates/node--event--featured-item.html.twig
  docroot/modules/custom/bos_content/modules/node_public_notice/templates/node--public-notice--featured-item.html.twig
Labels: Bug, Front End/UI, Back End
