Repository CityOfBoston/boston.gov-d8, pull requests merged in 2023-05, with the labels that each got.

#3078 DIG-2163 Extend length of time
  config/default/views.view.events_and_notices.yml
  config/default/views.view.public_notice.yml
Labels: Enhancement

#3079 DIG-2165 Extend timeout for content authors
  config/acquia_prod/autologout.settings.yml
Labels: Enhancement

#3083 DIG-2164 Add notification for content authors
  composer.json
  composer.lock
  config/default/content_moderation_notifications.content_moderation_notification.notify_content_creator.yml
  config/default/content_moderation_notifications.content_moderation_notification.review_content_submitted.yml
  config/default/core.extension.yml
  config/default/lightning_core.versions.yml
  config/default/user.role.content_author.yml
  config/default/user.role.content_editor.yml
  config/default/user.role.content_reviewer.yml
  config/default/user.role.site_administrator.yml
Labels: Enhancement, Back End

#3085 DIG-2059 Adjust language for contact information in events
  config/default/field.field.node.event.field_email.yml
  config/default/field.field.node.event.field_event_contact.yml
Labels: Bug, Enhancement, Back End

#3086 DIG-2060 Adjust order of contact information...
  docroot/modules/custom/bos_content/modules/node_event/templates/node--event.html.twig
Labels: Enhancement, Front End/UI

#3090 (production) building housing dup attachment
  .github/workflows/releaseNotes.yml
  composer.json
  config/acquia_dev/config_ignore.settings.yml
  config/acquia_dev/salesforce_logger.settings.yml
  config/acquia_prod/config_ignore.settings.yml
  config/acquia_prod/xmlsitemap.xmlsitemap.NXhscRe0440PFpI5dSznEVgmauL25KojD7u4e9aZwOM.yml
  config/acquia_stage/config_ignore.settings.yml
  config/default/config_split.config_split.acquia_dev.yml
  config/default/config_split.config_split.acquia_prod.yml
  config/default/config_split.config_split.local.yml
  config/default/node_buildinghousing.settings.yml
  config/default/salesforce_mapping.salesforce_mapping.building_housing_project_update.yml
  config/local/config_ignore.settings.yml
  config/local/salesforce_logger.settings.yml
  docroot/modules/custom/bos_content/modules/node_buildinghousing/css/node_bh_project.css
  docroot/modules/custom/bos_content/modules/node_buildinghousing/node_buildinghousing.links.menu.yml
  docroot/modules/custom/bos_content/modules/node_buildinghousing/node_buildinghousing.module
  docroot/modules/custom/bos_content/modules/node_buildinghousing/node_buildinghousing.routing.yml
  docroot/modules/custom/bos_content/modules/node_buildinghousing/src/Batch/SalesforceSyncBatch.inc
  docroot/modules/custom/bos_content/modules/node_buildinghousing/src/BuildingHousingUtils.php
  docroot/modules/custom/bos_content/modules/node_buildinghousing/src/EventSubscriber/SalesforceBuildingHousingUpdateSubscriber.php
  docroot/modules/custom/bos_content/modules/node_buildinghousing/src/Form/SalesforceSyncSettings.php
  docroot/modules/custom/bos_content/modules/node_buildinghousing/src/Plugin/Field/FieldFormatter/EntityReferenceTaxonomyTermBSPublicStageFormatter.php
  docroot/modules/custom/bos_content/modules/node_buildinghousing/templates/snippets/bh-project-timeline-document.html.twig
  docroot/modules/custom/bos_content/modules/node_buildinghousing/templates/snippets/bh-project-timeline-text.html.twig
  docroot/modules/custom/bos_core/bos_core.module
  docroot/themes/custom/bos_admin/bos_admin.theme
Labels: Deployed to Production, BuildingHousing

#3091 DIG-2177 Update 'My Workbench' to display 10 last edited pages
  .github/config/releaseNotesConfig.yml
  .github/workflows/releaseNotes.yml
  composer.lock
  config/acquia_prod/xmlsitemap.xmlsitemap.NXhscRe0440PFpI5dSznEVgmauL25KojD7u4e9aZwOM.yml
  config/default/config_split.config_split.acquia_prod.yml
  config/default/views.view.workbench_edited.yml
  config/default/views.view.workbench_my_edits.yml
  config/default/views.view.workbench_needs_review_cob.yml
  docroot/modules/custom/bos_components/modules/bos_city_score/bos_city_score.install
  docroot/modules/custom/bos_content/modules/bos_metrolist/src/Plugin/SalesforceMappingField/RelatedTermStrings.php
  docroot/modules/custom/bos_content/modules/node_status_item/node_status_item.module
  docroot/modules/custom/bos_core/src/BosCoreMediaEntityHelpers.php
Labels: Back End

#3092 DIG-2059 Adjust language for contact information in events
  config/default/field.field.node.event.field_email.yml
Labels: Back End

#3097 (develop) Update 'My Workbench' to display 10 last edited pages regard…
  config/default/views.view.workbench_edited.yml
  config/default/views.view.workbench_my_edits.yml
  config/default/views.view.workbench_needs_review_cob.yml
Labels: Bug, Back End

#3096 (develop) Adjust order of contact information in event sidebar - hotfix
  docroot/modules/custom/bos_content/modules/node_event/templates/node--event.html.twig
Labels: Back End

#3095 (develop) Adjust language for contact information in events - hotfix
  config/default/field.field.node.event.field_email.yml
  config/default/field.field.node.event.field_event_contact.yml
Labels: Back End

#3094 (develop) Add official .gov banner - hotfix
  docroot/themes/custom/bos_theme/bos_theme.theme
  docroot/themes/custom/bos_theme/css/bos_theme_overrides.css
  docroot/themes/custom/bos_theme/templates/layout/page.html.twig
  docroot/themes/custom/bos_theme/templates/snippets/site-banner.html.twig
Labels: Front End/UI

#3101 (production) Multiple Updates and Maintenance
  composer.lock
  config/default/field.field.node.event.field_email.yml
  config/default/field.field.node.event.field_event_contact.yml
  config/default/views.view.workbench_edited.yml
  config/default/views.view.workbench_my_edits.yml
  config/default/views.view.workbench_needs_review_cob.yml
  docroot/modules/custom/bos_components/modules/bos_email/bos_email.routing.yml
  docroot/modules/custom/bos_components/modules/bos_email/src/CobEmail.php
  docroot/modules/custom/bos_components/modules/bos_email/src/Controller/PostmarkAPI.php
  docroot/modules/custom/bos_components/modules/bos_email/src/EmailTemplateInterface.php
  docroot/modules/custom/bos_components/modules/bos_email/src/Templates/Contactform.php
  docroot/modules/custom/bos_components/modules/bos_email/src/Templates/MetrolistInitiationForm.php
  docroot/modules/custom/bos_components/modules/bos_email/src/Templates/MetrolistListingConfirmation.php
  docroot/modules/custom/bos_components/modules/bos_email/src/Templates/MetrolistListingNotification.php
  docroot/modules/custom/bos_components/modules/bos_email/src/Templates/Registry.php
  docroot/modules/custom/bos_content/modules/node_event/templates/node--event.html.twig
  docroot/themes/custom/bos_theme/bos_theme.theme
  docroot/themes/custom/bos_theme/css/bos_theme_overrides.css
  docroot/themes/custom/bos_theme/templates/layout/page.html.twig
  docroot/themes/custom/bos_theme/templates/snippets/site-banner.html.twig
Labels: Deployed to Production, Maintenance
