Repository CityOfBoston/boston.gov-d8, pull requests merged in 2023-10, with the labels that each got.

#3216 (stage) Maintenance, SSO, Metrolist Label and search
  .lando.yml
  composer.lock
  config/acquia_dev/captcha.settings.yml
  config/acquia_dev/key.key.iam_dir_sso_test_.yml
  config/acquia_dev/views.view.maillog_overview.yml
  config/acquia_prod/captcha.settings.yml
  config/acquia_prod/key.config_override.sf_oauth_consumer_key.yml
  config/acquia_prod/key.config_override.sf_oauth_consumer_secret.yml
  config/acquia_prod/key.key.iam_dir_sso_prod_.yml
  config/acquia_prod/key.key.salesforce_oauth_consumer_key.yml
  config/acquia_prod/key.key.salesforce_oauth_consumer_secret.yml
  config/acquia_prod/salesforce.salesforce_auth.dnd_prod.yml
  config/acquia_stage/captcha.settings.yml
  config/acquia_stage/key.key.iam_dir_sso_test_.yml
  config/default/block.block.website_feedback_form.yml
  config/default/config_split.config_split.acquia_dev.yml
  config/default/config_split.config_split.acquia_prod.yml
  config/default/config_split.config_split.acquia_stage.yml
  config/default/config_split.config_split.local.yml
  config/default/core.menu.static_menu_link_overrides.yml
  config/default/key.config_override.sf_oauth_consumer_key.yml
  config/default/key.config_override.sf_oauth_consumer_secret.yml
  config/default/key.key.salesforce_sandbox_oauth_consumer_key.yml
  config/default/key.key.salesforce_sandbox_oauth_consumer_secret.yml
  config/default/salesforce.salesforce_auth.moh_sandbox.yml
  config/default/salesforce_mapping.salesforce_mapping.building_housing_projects.yml
  config/default/salesforce_mapping.salesforce_mapping.metrolist_development.yml
  config/default/salesforce_mapping.salesforce_mapping.metrolist_unit.yml
  config/default/webform.webform.metrolist_listing.yml
  config/default/webform.webform.metrolist_listing_entry_form.yml
  config/local/config_split.patch.key.key.salesforce_sandbox_oauth_consumer_key.yml
  config/local/config_split.patch.key.key.salesforce_sandbox_oauth_consumer_secret.yml
  config/local/key.key.iam_dir_sso_test_.yml
  config/local/samlauth.authentication.yml
  docroot/modules/custom/bos_core/src/Form/QueryForm.php
  scripts/deploy/cob_utilities.sh
  scripts/local/lando-build-drupal.sh
Labels: Deployed to Stage, Metrolist, Maintenance

#3218 (production) Maintenance, SSO, Metrolist Label and search
  .lando.yml
  composer.lock
  config/acquia_dev/captcha.settings.yml
  config/acquia_dev/config_ignore.settings.yml
  config/acquia_dev/key.key.iam_dir_sso_test_.yml
  config/acquia_dev/views.view.maillog_overview.yml
  config/acquia_prod/captcha.settings.yml
  config/acquia_prod/config_ignore.settings.yml
  config/acquia_prod/config_split.patch.salesforce.settings.yml
  config/acquia_prod/key.config_override.sf_oauth_consumer_key.yml
  config/acquia_prod/key.config_override.sf_oauth_consumer_secret.yml
  config/acquia_prod/key.key.iam_dir_sso_prod_.yml
  config/acquia_prod/key.key.salesforce_oauth_consumer_key.yml
  config/acquia_prod/key.key.salesforce_oauth_consumer_secret.yml
  config/acquia_prod/salesforce.salesforce_auth.dnd_prod.yml
  config/acquia_stage/captcha.settings.yml
  config/acquia_stage/config_ignore.settings.yml
  config/acquia_stage/key.key.iam_dir_sso_test_.yml
  config/default/block.block.website_feedback_form.yml
  config/default/config_split.config_split.acquia_dev.yml
  config/default/config_split.config_split.acquia_prod.yml
  config/default/config_split.config_split.acquia_stage.yml
  config/default/config_split.config_split.local.yml
  config/default/core.menu.static_menu_link_overrides.yml
  config/default/key.config_override.sf_oauth_consumer_key.yml
  config/default/key.config_override.sf_oauth_consumer_secret.yml
  config/default/key.key.salesforce_sandbox_oauth_consumer_key.yml
  config/default/key.key.salesforce_sandbox_oauth_consumer_secret.yml
  config/default/salesforce.salesforce_auth.moh_sandbox.yml
  config/default/salesforce.settings.yml
  config/default/salesforce_mapping.salesforce_mapping.building_housing_projects.yml
  config/default/salesforce_mapping.salesforce_mapping.metrolist_development.yml
  config/default/salesforce_mapping.salesforce_mapping.metrolist_unit.yml
  config/default/webform.webform.metrolist_listing.yml
  config/default/webform.webform.metrolist_listing_entry_form.yml
  config/local/config_ignore.settings.yml
  config/local/config_split.patch.key.key.salesforce_sandbox_oauth_consumer_key.yml
  config/local/config_split.patch.key.key.salesforce_sandbox_oauth_consumer_secret.yml
  config/local/key.key.iam_dir_sso_test_.yml
  config/local/samlauth.authentication.yml
  config/travis/config_ignore.settings.yml
  docroot/modules/custom/bos_core/src/Form/QueryForm.php
  scripts/deploy/cob_utilities.sh
  scripts/local/lando-build-drupal.sh
Labels: Deployed to Production, Metrolist, Maintenance

#3224 DIG-2929 Internal links
  docroot/modules/custom/bos_components/modules/bos_link/bos_link.module
  docroot/modules/custom/bos_components/modules/bos_link/src/Plugin/Field/FieldWidget/COBLinkWidget.php
  docroot/modules/custom/bos_core/bos_core.module
Labels: Enhancement

#3225 DIG-2929 Internal links
  config/default/core.entity_form_display.paragraph.internal_link.default.yml
Labels: Enhancement

#3226 DIG-2931
  docroot/modules/custom/bos_components/css/component-theme.css
  docroot/modules/custom/bos_components/modules/bos_link_collections/templates/paragraph--group-of-links-mini-grid.html.twig
Labels: Enhancement

#3227 DIG-2931 Hide title bar
  docroot/modules/custom/bos_components/modules/bos_grid/bos_grid.module
  docroot/modules/custom/bos_components/modules/bos_link_collections/bos_link_collections.module
Labels: Enhancement

#3228 DIG-2931 Hide title bar
  docroot/modules/custom/bos_components/css/component-theme.css
Labels: Enhancement

#3231 DIG-3014 sidebar
  docroot/themes/custom/bos_theme/css/bos_theme_overrides.css
  docroot/themes/custom/bos_theme/templates/snippets/topic-nav.html.twig
Labels: Enhancement

#3233 (Production) Drupal Maintenance
  .travis.yml
  composer.json
  composer.lock
  config/acquia_prod/key.config_override.sf_oauth_prod_consumer_key.yml
  config/acquia_prod/key.config_override.sf_oauth_prod_consumer_secret.yml
  config/acquia_prod/key.key.salesforce_oauth_consumer_key.yml
  config/acquia_prod/key.key.salesforce_oauth_consumer_secret.yml
  config/default/config_split.config_split.acquia_dev.yml
  config/default/config_split.config_split.acquia_prod.yml
  config/default/config_split.config_split.acquia_stage.yml
  config/default/config_split.config_split.local.yml
  config/default/editor.editor.rich_text.yml
  config/default/field.field.media.document.field_document.yml
  config/default/filter.format.rich_text.yml
  config/default/lightning_core.versions.yml
  config/default/pathauto.settings.yml
  config/local/config_split.patch.ape.settings.yml
  config/local/config_split.patch.system.performance.yml
  docroot/libraries/dompurify/dist/purify.cjs.js
  docroot/libraries/dompurify/dist/purify.cjs.js.map
  docroot/libraries/dompurify/dist/purify.es.js
  docroot/libraries/dompurify/dist/purify.es.js.map
  docroot/libraries/dompurify/dist/purify.js
  docroot/libraries/dompurify/dist/purify.js.map
  docroot/libraries/dompurify/dist/purify.min.js
  docroot/libraries/dompurify/dist/purify.min.js.map
  docroot/modules/custom/bos_core/bos_core.install
  patches/lightning_scheduler.patch
  scripts/.config.yml
  scripts/deploy/cob_utilities.sh
Labels: Deployed to Production, Maintenance

#3235 DIG-2931 Hide title bar
  docroot/modules/custom/bos_components/modules/bos_grid/bos_grid.module
  docroot/modules/custom/bos_components/modules/bos_link_collections/bos_link_collections.module
Labels: Enhancement

#3236 DIG-3014 Sidebar mobile view
  docroot/modules/custom/bos_content/modules/node_article/templates/node--article.html.twig
  docroot/modules/custom/bos_content/modules/node_department_profile/templates/node--department-profile.html.twig
  docroot/modules/custom/bos_content/modules/node_place_profile/templates/node--place-profile.html.twig
  docroot/modules/custom/bos_content/modules/node_program_initiative_profile/templates/node--program-initiative-profile.html.twig
  docroot/themes/custom/bos_theme/css/bos_theme_overrides.css
  docroot/themes/custom/bos_theme/templates/snippets/topic-nav.html.twig
Labels: Enhancement

#3237 DIG-3014 Sidebar mobile view
  docroot/themes/custom/bos_theme/css/bos_theme_overrides.css
  docroot/themes/custom/bos_theme/templates/snippets/topic-nav.html.twig
Labels: Enhancement

#3239 DIG-3014 Sidebar on mobile
  docroot/themes/custom/bos_theme/css/bos_theme_overrides.css
  docroot/themes/custom/bos_theme/templates/snippets/topic-nav.html.twig
Labels: Enhancement

#3240 DIG-3014 Sidebar on mobile
  docroot/themes/custom/bos_theme/templates/snippets/topic-nav.html.twig
Labels: Enhancement

#3241 DIG-3014 Mobile sidebar update
  docroot/modules/custom/bos_content/modules/node_topic_page/templates/node--topic-page.html.twig
  docroot/themes/custom/bos_theme/css/bos_theme_overrides.css
  docroot/themes/custom/bos_theme/templates/snippets/topic-nav.html.twig
Labels: Enhancement

#3242 DIG-3014 Sidebar on mobile
  docroot/modules/custom/bos_content/modules/node_post/templates/node--post.html.twig
  docroot/themes/custom/bos_theme/css/bos_theme_overrides.css
Labels: Enhancement

#3244 DIG-3014 Sidebar on mobile
  docroot/themes/custom/bos_theme/css/bos_theme_overrides.css
Labels: Enhancement
