Repository CityOfBoston/boston.gov-d8, pull requests merged in 2024-09, with the labels that each got.

#3584 DIG-4655 - Moderation Dashboard
  config/default/core.extension.yml
Labels: Enhancement

#3598 DIG-5025 Hide YouTube channel question in 'video' component
  config/default/field.field.paragraph.video.field_is_channel.yml
  docroot/modules/custom/bos_components/modules/bos_video/bos_video.module
Labels: Enhancement

#3612 DIG-5116 Remove Covid 19 statements from website
  docroot/modules/custom/bos_components/modules/bos_translate/js/translate.js
Labels: Bug, Enhancement

#3613 (Develop) DIG-5116 Add data-nosnippet to translation block
  docroot/modules/custom/bos_components/modules/bos_translate/js/translate.js
  docroot/themes/custom/bos_theme/templates/snippets/secondary-nav.html.twig
Labels: Enhancement

#3617 DIG-4655 Moderation Dashboard
  docroot/themes/custom/bos_theme/css/bos_theme_overrides.css
Labels: Enhancement

#3618 DIG-4655 Moderation Dashboard
  docroot/themes/custom/bos_theme/css/bos_theme_overrides.css
Labels: Enhancement

#3620 (dev) DIG-5067: Updated Search Bar Component Styling, Metrolist Drupal Config
  docroot/modules/custom/bos_components/modules/bos_web_app/apps/metrolist/metrolist.libraries.yml
  docroot/modules/custom/bos_components/modules/bos_web_app/apps/metrolist/src/components/SearchBar/SearchBar.scss
  docroot/modules/custom/bos_components/modules/bos_web_app/apps/metrolist/src/components/SearchBar/index.js
Labels: Enhancement, Metrolist

#3621 (dev) DIG-5067-Updated-Libraries-YML-to-Include-All-Bundles
  docroot/modules/custom/bos_components/modules/bos_web_app/apps/metrolist/metrolist.libraries.yml
Labels: Enhancement, Metrolist
